### ISSUE TITLE
New import path for xz package

### ISSUE THREAD

**Issue by xi2** [zbindenren/gym#2]
There is a new import path for the `xz` package used in `util.go` and `glide.yaml`. It is `github.com/xi2/xz`. The old one will cease to work at some point. Sorry for the inconvenience.

**Comment by udondan** [comment]
It did.

    $ go get github.com/zbindenren/gym
    package xi2.org/x/xz: unrecognized import path "xi2.org/x/xz" (https fetch: Get https://xi2.org/x/xz?go-get=1: dial tcp: lookup xi2.org on 1.2.3.4:5: no such host)

**Comment by zbindenren** [comment]
I will fix it when I am back from kubecon.

**Comment by udondan** [comment]
Have fun! Hope they have enough seats this year. 😆
